name: alleled
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python>=3.8
  - biopython>=1.83
  - pandas>=2.0.3
  - pysam>=0.22.1
  - snakemake
  - pbaa>=1.0.3,<2
  - samtools>=1.20,<2
  - bbmap>=39.8,<40
  - exonerate>=2.4.0,<3
  - clustalo>=1.2.4,<2
  - minimap2>=2.1.1,<3
  - pip
  - pip:
    - setuptools>=40.8.0
    - cffi>=1.15.0,!=1.17.0
    - .
platforms:
  - osx-64
  - linux-64
  - linux-aarch64
